#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
./mvnw clean site:site site:stage

echo "Copying site resources into asf-site repo"
cp -rvf target/staging/* ../creadur-site/whisker/ > /dev/null
echo "DONE."

echo "Copying JS/CSS resources into generated reports"
cp -rvf src/site/javadocFont/* ../creadur-site/whisker/apidocs/ > /dev/null
cp -rvf src/site/javadocFont/* ../creadur-site/whisker/testapidocs/ > /dev/null
cp -rvf src/site/javadocFont/* ../creadur-site/whisker/xref/ > /dev/null
cp -rvf src/site/javadocFont/* ../creadur-site/whisker/xref-test/ > /dev/null

for module in "apache-whisker-velocity" "apache-whisker-app" "apache-whisker-xml" "apache-whisker-scan" "apache-whisker-model" "apache-whisker-maven-plugin" "apache-whisker-cli"
 do
  cp -rvf src/site/javadocFont/* ../creadur-site/whisker/$module/apidocs/ > /dev/null
  cp -rvf src/site/javadocFont/* ../creadur-site/whisker/$module/testapidocs/ > /dev/null
  cp -rvf src/site/javadocFont/* ../creadur-site/whisker/$module/xref/ > /dev/null
  cp -rvf src/site/javadocFont/* ../creadur-site/whisker/$module/xref-test/ > /dev/null
 done

echo "DONE."